### ISSUE TITLE
don't save hasMany/queryInverse with many-to-many

### ISSUE THREAD

**Issue by muziejus** [pouchdb-community/relational-pouch#114]
I suspect I'm over-assuming here, but:

Is there a way to use queryInverse and `db.findHasMany` to make it so I only have to save a many-to-many relationship on one side? something like:

```javascript
await db.allDocs(); //=>
/*
{ docs:
  [
    { _id: "author_1_1", _rev: "...", data: { name: "Stephen King", books: [] } },
    { _id: "author_1_2", _rev: "...", data: { name: "Peter Straub", books: [] } },
    { _id: "book_1_1", _rev: "...", data: { title: "The Talisman", authors: [1, 2] } }
  ]
}
*/
await db.rel.findHasMany("book", "author", 1); // =>
/*
[
  {id: 1, title: "The Talisman", authors: [1, 2]},
  ...
]
*/
```

My testing seems to point to no, but I'm not sure if that means I'm doing something wrong or the answer actually is no.

**Comment by broerse** [comment]
No, not yet. We were thinking about it and like to implement `save: true` for Many to Many https://github.com/pouchdb-community/ember-pouch#relationships 
On the relational pouch side, this would need the change you talk about here.

**Comment by muziejus** [comment]
Thanks.
