### ISSUE TITLE
how to get sort data?

### ISSUE THREAD

**Issue by bilalswiftsolutions** [pouchdb-community/relational-pouch#169]
I try using sort , but didn't work do i need to do something different?

```
try {
  const result = await pouchdb.rel.find('staff', { limit: 20, sort: [{ name: 'desc' }] });

} catch (err) {
  console.log(err);
}
```

**Comment by broerse** [comment]
There is no sort. See: https://github.com/pouchdb-community/relational-pouch/tree/master#dbrelfindtype-options

We do the sorting in Ember Data ourselves https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-authors.js
