### ISSUE TITLE
Can not query documents

### ISSUE THREAD

**Issue by MishUshakov** [pouchdb-community/relational-pouch#89]
Hey guys, how to fix this?

Input

`db.rel.find('author')`

output

```
(node:57648) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: db.find is not a function
(node:57648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by UrGuardian4ngel** [comment]
Just ran into the exact same issue...

But it looks like the `db.find` method requires the `pouchdb-find`, as per [API documentation](https://pouchdb.com/api.html#query_index).

So just install that extension:

```bash
$ yarn add pouchdb-find
# or
$ npm install --save pouchdb-find
```

and register the plugin:

```diff
 const PouchDB = require('pouchdb');
+PouchDB.plugin(require('pouchdb-find'));
```

**Comment by broerse** [comment]
We just made  `pouchdb-find` a peer dependency in v.3.0.0 that should make this more clear.
