### ISSUE TITLE
Confused about "hasMany" relationship (see description below)

### ISSUE THREAD

**Issue by jetamartin** [pouchdb-community/relational-pouch#99]
I'm confused about using "hasMany" in the schema definition. This confusion arose from the  description of "Don't save hasMany" (https://github.com/pouchdb-community/relational-pouch#dont-save-hasmany).  

The description states:  "By default relational-pouch will store the child ids of an Many-to-one relationship as a property on the many side (the parent)." This statement leads me to believe that appropriate child ids are added automatically based on how you define the schema?   Is that true? I don't see that happening in my code...I have to explicitly add the values. 

Also It doesn't appear that is the case based on other examples of schema provided in the documentation. For example,  in this example (https://github.com/pouchdb-community/relational-pouch#many-to-one-relationships). The id's of the books were explicitly added to the authors books property via the db.rel.save (e.g., books: [6, 7]). So that seems to be in direct conflict with the statement noted above ("By default relational-pouch will store the child ids......."). 

Can someone clarify what the statement  really means?  Is it automatic or not? If not what is meant by "By default". I'm confused and I'm guessing I'm not the only one. 

Another related note: the "Don't save hasMany" documentation goes on to say: "This will tell relational-pouch to not save the book ids on the author, and use a query using db.find to look for the related books."

Does user need to explicitly issue db.rel.find to retrieve them? Does relational-pouch issues a db.find automagically under the covers to look for the related books?  Based on the documentation it sounds like the later.  Can someone clarify? If the user needs to explicitly issue a db.rel.find() can someone provide an example?  

The documentation goes on to say: 

 "Since this uses db.rel.findHasMany(type, belongsToKey, belongsToId) internally, you also need an index as specified there, where belongsToKey is the field specified in the queryInverse option."

What does it mean by "you also need an index"? Is this meant to be an explanation for why "author" is provided as the value of queryInverse option????  Or does this mean that the user need to do something in addition to what is specified in the example???? Such vagueness! If it's the latter can someone provide an example of exactly what the user needs to do to retrieve the books for an author. 

Examples add to the documentation would go a LONG way to clarifying the documentation. 

Thanks, 
Jet

**Comment by broerse** [comment]
@jetamartin Yes it is automatic when you use `queryInverse` but you need to add `pouchdb-find` to your project. I understand that it is confusing but you need indexes for `pouchdb-find` . See https://github.com/pouchdb-community/ember-pouch/blob/master/addon/adapters/pouch.js#L209 where we create them. See also [mango-queries](https://pouchdb.com/guides/mango-queries.html) Perhaps we should try to add a working example and improve the readme. The [ember-pouch](https://github.com/pouchdb-community/ember-pouch) addon maybe interesting to look at.

**Comment by jetamartin** [comment]
@broerse Thanks for the reply to my first question. BTW, I do have pouchdb-find installed in my project and it didn't seem to be automatic in my code. Hence my questions. Maybe I'm doing something wrong? I'm assuming the code you referenced in your response was intended to show that index is automatically created? 

Any thoughts or comments about my other questions? 

From my perspective more examples are ABSOLUTELY needed given the vagueness and ambiguity of the documentation. As a user I have lots of feedback on the documentation. It needs a LOT of work.

**Comment by broerse** [comment]
@jetamartin the second question comes from the confusing  "By default relational-pouch will store the child ids of an Many-to-one relationship as a property on the many side (the parent)." So the use of relational-pouch without `queryInverse` is considered the default. In that case using relational-pouch will need you to store the child ids on the many side as described in the doc. If you use `queryInverse`  you do not. We are not native English speakers so please make a PR to improve this sentence.

**Comment by jetamartin** [comment]
@broerse, 
Thanks for the reply.  Thanks for letting me know that English is really a second language of the developers/documenters. The root of my confusion on "one-to-many"  arose from two issues:

1) As I noted my reply above  I'm not seeing the child ids being automatically added as a property on the many side as you say. I'm assuming I  must be doing something wrong in my code.  

2)  The example provided in the documentation for  the "one-to-many" relationship shows the the child ids (books) being added manually (e.g., books: [1, 2]) via the db.rel.save(). Why would the only example provided not show the "default" behavior? That makes no sense to me and created some of the confusion.  I would suggest that you change the example to show the 'default' behavior and add a note at the bottom of the example stating that the user could manually add the childIDs if they'd like. 

The other points of confusion that I noted arise because in numerous places the language in the documentation creates ambiguity/vagueness on what is "automatic" system behavior (i.e., requires no explicit user action)  vs what actions must be taken explicitly taken by the user. The reader is left with the question...do I need to do something in addition to what is being shown in the example? or is the documentation merely describing how it uses the parameters the user provides? Explaining what/how the system accomplishes something or how it makes use of the parameters provided by the user is great but the documentation needs to be clear on when the user needs to do something. 

Another general point I'd like to see addressed in the documentation is the relationship of relational-pouch to pouchdb. My understanding is that relational-pouch sits on top of pouchdb but can a user call pouchdb API methods directly when they have relational-pouch installed. Are the relational-pouch APIs meant to provide a "complete set of API's" needed or is it expected and allowed for the user to make use of pouchdb API's to accomplish certain "tasks". 

An accompanying diagram showing the relationship of relational-pouch db would be useful along with a description that denotes pouchdb API's that can and can't be used with relational-pouch. (I realize some can't be used directly because of the "compound" key required for relational-pouch). As I stated I don't know whether relational-pouch is intended to provide an all encompassing set of APIs or its intended to provide a subset of APIs as portrayed by the picture. 
  
______________________________________________
|                         User App                              |
|---------------|------------------|--------|
--------------- v  --------              |
| relational-pouch APIs    |              |
_____________|_____________|              |
------------ |--------------------- |--------
|                   v   pouchdb APIs         v           |
-------------------------------------------

Perhaps the most important thing you could do to clarify the documentation is to create documentation/video that shows how someone would use the relational-pouch apis to build a simple application. This would serve to clarify many of the ambiguities in the documentation and it would boost usage of relational-pouch.  PouchDB github shows an example app via documentation and via a video (narrated by Nolan Lawson). Perhaps you could have Nolan create a video for you guys?  

That's all for now. 

Hoping someone can address my other outstanding issue re: not being able to "perform" relational-pouchdb  operations (e.g., db.rel.save()) from the Chrome console. If I can't do that then it's a showstopper for me. I'll have to abandon this plugin.

**Comment by broerse** [comment]
@jetamartin I try to explain that if you use `queryInverse` with a model like [this](https://github.com/broerse/ember-cli-blog/blob/master/app/models/author.js#L6) you don't store the hasmany `posts` array. See [the record](https://martinic.couchcluster.com/bloggr/author_2_D8F61FBC-A9C4-0318-851B-228507CDC032) in CouchDB.

I keep an example up-to-date that uses relational-pouch. Perhaps try that. https://github.com/broerse/ember-cli-blog or take a look at the big https://github.com/HospitalRun/hospitalrun-frontend

**Comment by courageDeveloper** [comment]
I am so glad to see this post made by @jetamartin , i thought i was the only one facing this as well. I am having a difficult time implementing db.rel.findHasMany and from the documentation i can't really tell if i am on the right path or not.
